### ISSUE TITLE
Labels for indicating topic of issues

### ISSUE THREAD

**Issue by Mikerah** [ChainSafeSystems/Sharding#4]
@GregTheGreek just posted some labels for triaging issues across our repositories. 

This is very important so that we can easily prioritize the work that needs to be done at a glance and gives contributors an idea of how they can easily contribute. The github default labels can easily trivialize some tasks and make other tasks seem important when they are not.

I am starting this issue to raise awareness.

**Comment by GregTheGreek** [comment]
Let's play around with the labels in this repo, and once We're satisfied I'll just run the script on all of our repos.

Instead of changing the labels in the repo itself, please propose the label change in here with the `name`, `color` (in hex) and `motivation` for the label.

**Comment by GregTheGreek** [comment]
closing for a test
