### ISSUE TITLE
Redeploy all libraries under ChainSafe npm account

### ISSUE THREAD

**Issue by GregTheGreek** [ChainSafeSystems/Sharding#6]
We need to redploy all the repos under chainsafe's npm account.

- [x] Remove SSZ-JS from mikerah
- [x] Remove lodestar from gregthegreek
- [ ] add SSZ-JS to npm
- [ ] add lodestar to npm

**Comment by Mikerah** [comment]
I have deprecated ssz-js released under my account with a message saying to install the ChainSafe one.
